### ISSUE TITLE
Rolling Upgrades

### ISSUE THREAD

**Issue by glasschef** [opscode-cookbooks/chef-server-cluster#12]
Many customers would love to have zero-downtime, rolling upgrades for Chef Server.  With the current structure of the Chef Server, this isn't really feasible, but with the introduction of this Chef Server Cluster project maybe this is something that can be built in.

**Comment by paulmooring** [comment]
I'm closing this issue out as it's a feature/enhancement that belongs in the server rather than this cookbook.
