### ISSUE TITLE
Support for clouds / virtualization other than AWS

### ISSUE THREAD

**Issue by adamedx** [opscode-cookbooks/chef-server-cluster#18]
Right now, it looks like you have to use AWS to host your Chef Server via this recipe. I'd like to be able to host on a dev box via vagrant, or use a cloud provider like OpenStack, GCE, Azure, etc. I'd like to see this genericized so it can support an arbitrary virtualization substrate.

**Comment by hh** [comment]
Any discussion / motion on this? I was hoping to target digital-ocean.

**Comment by paulmooring** [comment]
Given the authors' internal usage of this cookbook, this feature is not likely to be added unless it comes from the community along with a PR.  I'm closing this issue out 'wontfix' for now, but I'd happily consider/review code to add this feature if it comes in later.
