### ISSUE TITLE
Analytics fails to complete due to an ssl certificate issue

### ISSUE THREAD

**Issue by larrywright** [opscode-cookbooks/chef-server-cluster#24]
I'm seeing this consistently when I run this cookbook. It creates the backend and frontend fine, but then fails when creating the analytics server. It seems to be related to the ssl certificate that's being generated.

I'll dig into this tomorrow, but I wanted to mention it there in case anyone else has seen this.

                [2015-01-08T19:09:02-05:00] ERROR: service[nginx] (dynamically defined) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
                ---- Begin output of /opt/opscode-analytics/embedded/bin/sv restart /opt/opscode-analytics/service/nginx ----
                STDOUT: timeout: down: /opt/opscode-analytics/service/nginx: 1s, normally up, want up
                STDERR: 
                ---- End output of /opt/opscode-analytics/embedded/bin/sv restart /opt/opscode-analytics/service/nginx ----
                Ran /opt/opscode-analytics/embedded/bin/sv restart /opt/opscode-analytics/service/nginx returned 1
                [2015-01-08T19:09:02-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
                STDERR: [2015-01-08T19:06:42-05:00] ERROR: Could not parse hint file at /etc/chef/ohai/hints/ec2.json: internal error: object not a hash or array
                Generating RSA private key, 2048 bit long modulus
                .....................................................................................+++
                ..+++
                e is 65537 (0x10001)
                problems making Certificate Request
                140121255708328:error:0D07A098:asn1 encoding routines:ASN1_mbstring_ncopy:string too short:a_mbstr.c:147:minsize=1
                ---- End output of opscode-analytics-ctl reconfigure ----
                Ran opscode-analytics-ctl reconfigure returned 1
                [2015-01-08T19:09:02-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by toddmichael** [comment]
@larrywright noticed you closed this without comment. curious if you solved and how.  much obliged.

**Comment by jtimberman** [comment]
I've encountered this intermittently. Not sure why but it corrects itself on another converge.

**Comment by larrywright** [comment]
I closed this because it wasn't an issue with the cookbook itself, but I probably should have noted what the issue actually was. 

The root cause here was that the fqdn was too long (auto-generated AWS hostname). It exceeded the 64-bit limit of OpenSSL, and so generating the certificate fails. Switching to a shorter hostname resolves the issue.
