### ISSUE TITLE
Convert to chef-provisioning-aws, but be agnostic

### ISSUE THREAD

**Issue by jtimberman** [opscode-cookbooks/chef-server-cluster#28]
As much as possible, the setup-provisioner recipe can be fairly cloud/driver agnostic. We should default to the use of chef-provisioning-aws, but allow for other providers by making the with_driver argument be an attribute. The with_machine_options method already takes an attribute that is a hash. That is 'aws' for now but could be a more general named attribute.

We'd also need to have an attribute of the chef-provisioning gem that needs to be installed via chef_gem to make it go, and ideally support the chef 12.1.0 compile time property.

**Comment by Craft---** [comment]
:+1:
