### ISSUE TITLE
Remove standalone recipe

### ISSUE THREAD

**Issue by jtimberman** [opscode-cookbooks/chef-server-cluster#30]
It doesn't make sense to have a standalone recipe for a "cluster" cookbook. We have the [chef-server](https://supermarket.chef.io/cookbooks/chef-server) to setup a standalone Chef Server 12 system.

**Comment by poliva83** [comment]
I sort of disagree with this. In our infrastructure we have standalone master servers that we upload policy to and then replicate to servers in HA topology. It's preferable to only need to deal with single top level cookbook for deployments. The cluster cookbook could just depend on chef-server cookbook though to run its standalone recipe.

**Comment by jtimberman** [comment]
There's some background here. The standalone recipe predates the use of not only Chef Provisioning in *this* cookbook, but also (obviously?) the chef-server cookbook refactor to support Chef Server 12. As it predates the use of Chef Provisioning, there isn't a recipe to use Chef Provisioning to create a standalone machine resource, nor do we want to add such, as it increases the complexity in maintaining this cookbook.

Separate cookbooks draws a clear delineation of purpose. Depending on the chef-server cookbook is definitely something we don't want to do just for the use case of having a standalone recipe.

If you're replicating to multiple Chef Servers, have you looked into [Chef Replication](http://docs.chef.io/server_replication.html)? Working with that add-on is something we want to support with this cookbook in the longer term - though we obviously need HA support before that :smile_cat:.

**Comment by poliva83** [comment]
I did dig deeply into Chef Replication the last week or so with the original goal of syncing from Standalone chef server to an HA chef server. This is why was sort mentioning you may end up needed a modified standalone recipe that runs `ec_sync_server`. 

But anyway the current state of Chef Replication unfortunately doesn't really cover our needs for High Availability. It is also disappointing that currently only focusses on syncing policy and not any RBAC information.

I have open ZenDesk #3136 ticket about chef replication.

**Comment by mfdii** [comment]
(chef-server)[https://supermarket.chef.io/cookbooks/chef-server] doesn't provide any of the installation for add-ons. The nice thing about the standalone recipe is that you also got the add-ons installed.

**Comment by jtimberman** [comment]
I left a comment on https://github.com/chef-cookbooks/chef-server/pull/77.
