### ISSUE TITLE
reporting databag is missing

### ISSUE THREAD

**Issue by vinyar** [opscode-cookbooks/chef-server-cluster#34]
Seems the recipe is looking for a data bag that's not in the readme.md

https://github.com/opscode-cookbooks/chef-server-cluster/blob/384cddc793d314287a14d300659c0329984bb38b/recipes/bootstrap.rb#L29

pretty please :)

**Comment by jtimberman** [comment]
For now https://github.com/jtimberman/chefconf2015-chef-repo/blob/master/data_bags/secrets/README.md

**Comment by vinyar** [comment]
thumbs up!
